### ISSUE TITLE
Customize makeprg for a compiler (or how to run :Dispatch zeus rspec)

### ISSUE THREAD

**Issue by aaronjensen** [tpope/vim-dispatch#10]
I'd like to be able to run rspec w/ zeus through :Dispatch. I can do this, but then I don't get the compiler set to `rspec` so I don't get the right errorformat.

**Comment by spastorino** [comment]
@tpope had a chance to check out some things and `compiler_split` is never called.

https://github.com/tpope/vim-dispatch/blob/11420880486936bcbadd271e818e22337a874501/autoload/dispatch.vim#L857 that's true because executable is `--`.

Which is what Make does here https://github.com/tpope/vim-dispatch/blob/11420880486936bcbadd271e818e22337a874501/plugin/dispatch.vim#L19-L21

Just in case, I'm using `Make`, unsure if I should use `Dispatch` in this case.

**Comment by spastorino** [comment]
Just in case to carify further, I have a `.projectionist.json` file in the project with the following content ...

```
$ cat .projections.json 
{
	"*": {
		"make": "~/src/bin/remote-build.sh ./x.py"
	}
}
```

And this is why `:Make build stuff` works and expands to `~/src/bin/remote-build.sh ./x.py build stuff` I'm not sure why executable is `--` in vim-dispatch and all the things that are going on here :). Happy to keep providing more info.

**Comment by tpope** [comment]
If you're using Projectionist's `"make"`, then Projectionist will pick the compiler, not Dispatch. Projectionist does try to ask Dispatch though:

https://github.com/tpope/vim-projectionist/blob/438b58aab54624e554d71063a69ba3d1e1bfbc2f/autoload/projectionist.vim#L603-L615

**Comment by spastorino** [comment]
Right, so https://github.com/tpope/vim-projectionist/blob/8dda7acb7e24b44ef691ba19b35f585e97e91b30/autoload/projectionist.vim#L604 gives me `remote-build` without the `.sh` but anyway that's not a compiler because it's a custom command and then as you've said asks `Dispatch` and gives me wrong stuff I guess because of https://github.com/tpope/vim-dispatch/blob/11420880486936bcbadd271e818e22337a874501/autoload/dispatch.vim#L633-L634 checking a bit ...

**Comment by spastorino** [comment]
Ok, found what's going on, it's not a direct translation what needs to be done from makepkg to `dispatch_compilers`.

makepkg works the following ...

```
" CompilerSet makeprg=remote-build.sh\ x.py
```

for `dispatch_compilers` I need ...

```
let g:dispatch_compilers = {
      \ 'x.py': 'rustc',
      \ '~/src/bin/remote-build.sh ./x.py': 'rustc'}
```

and not ...

```
let g:dispatch_compilers = {
      \ 'x.py': 'rustc',
      \ 'remote-build.sh x.py': 'rustc'}
```

as I've originally said.

Maybe https://github.com/tpope/vim-projectionist/blob/8dda7acb7e24b44ef691ba19b35f585e97e91b30/autoload/projectionist.vim#L604 could be adjusted to make it more similar to hoe makepkg works.
