### ISSUE TITLE
Make it so Dispatch does not auto-close upon completion of job

### ISSUE THREAD

**Issue by ianks** [tpope/vim-dispatch#102]
Is there a way to invoke this setting? I know this is similar to just `:!`, but I am so fond of `:Focus` that I would like to be able to use it for this need!

:wink:

**Comment by symbolix** [comment]
Hi, has there been any news on this topic. I am aware that the issue is closed, however, I am also trying to keep the pane that runs the :Make! process open so that I can keep it around and constantly observe the verbose. Also, keeping that pane open and always use that specific pane for the next :Make! is something I would love to see.

I have tried couple of hacks to keep that pane open, but it is really not an option. The pane would die, will stick around, then the next :Make! will spawn another pane that will die as well.

I can understand that `:copen` already has the verbose, however, the need to have a live pane that constantly displays the verbose of the make command would be handy.

**Comment by tpope** [comment]
The only thing that has changed is the quickfix window now always opens on a nonzero exit status, making the concern about missing a failure all but completely moot.

**Comment by symbolix** [comment]
Sure. I have recently started using vim-dispatch and it is a great plugin. It is probably a very personal preference, wanting to have a tmux pane that is called 'make' and stays always open, and the continuous verbose of the **:Make** command keeps streaming in there, every time I run it.

The quickfix buffer is definitely the star of the show (not worried that I will miss something at all), a secondary tmux pane that I can keep an eye on from time to time would be a bonus.
