### ISSUE TITLE
I cannot execute a command after Dispatch has completed

### ISSUE THREAD

**Issue by m42e** [tpope/vim-dispatch#114]
I try to do xslt processing into an output file. I use Dispatch to trigger the command. After it completes I want to reaload the buffer of the output file(s). 
So I mapped F10 to:
```:Dispatch | checktime``` by ```map <F10> :Dispatch \| checktime<CR>```

But this does not work as expected. It seems it does not start anything.

**Comment by tpope** [comment]
`au cgetfile* checktime` might work.

**Comment by mellery451** [comment]
I think I might have a similar use case but I'm not sure the autocmd suggested above would work in my case (because the command I want to run is not strongly associated with a file?). I currently have:

   nmap <leader>M :Dispatch<CR>:YcmCompleter ClearCompilationFlagCache<CR>

I need to ensure that the Ycm command runs after the make running under Dispatch is complete. Would my map above accomplish this? If not, do you have advice on how to get the Ycm command to run after the dispatch is complete?

Thanks!

**Comment by tpope** [comment]
It won't, but `au cgetfile * YcmCompleter ClearCompilationFlagCache` would probably work for that too. If you only want to run it *some* of the time, you can wrap it in an `if` statement based on something like `&makeprg` or `&errorformat`.
