### ISSUE TITLE
Output different when using tmux, related to shift in/out characters

### ISSUE THREAD

**Issue by shmup** [tpope/vim-dispatch#119]
I'm not sure why tmux handles shift out/in characters (particularly with Dispatch) differently, but maybe it's something with my tmux configuration?

Also when I'm not using tmux I properly see the "Finished: ____" result.

The bottom example is tmux.

![output](https://cloud.githubusercontent.com/assets/118710/6954577/473754a4-d8a1-11e4-8cd7-5620f6845330.png)

**Comment by tpope** [comment]
It's because the tmux adapter intercepts the pane output directly rather than piping through `tee`. Are those shift in/out characters supposed to do anything? You could try stripping them out in the tmux handler (the same way we currently do color codes and `\r`).

The `Finished` notification gets lost in the resize. Not a big deal because the resize itself is noticable.
