### ISSUE TITLE
Feature request: if text is selected, use it when running :'<,">FocusDispatch!

### ISSUE THREAD

**Issue by devth** [tpope/vim-dispatch#134]

**Comment by tpope** [comment]
What happens if there is more than one line? How do you disambiguate between a global and window focus? Why `:FocusDispatch` more important to have this feature than, say, `:Dispatch` itself?

Personally I the following map to address this and countless other use cases:

   cmap <C-R><C-L> <C-R>=getline('.')<CR>

**Comment by devth** [comment]
Whoa, that's way better! :cool:
