### ISSUE TITLE
Adapter for background jobs

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-dispatch#188]
With the release of Vim 8, we got support for [background jobs](http://vimhelp.appspot.com/eval.txt.html#job_start%28%29). Which I can see as something I'd like to be incorporated into dispatch.vim.

I'd gladly work on this myself, but I wanted to test out the waters and ask prior to starting developing this as a pull request to dispatch.vim itself, or as a plugin in the likes of [vim-dispatch-neovim](https://github.com/radenling/vim-dispatch-neovim).
If so, could you provide any directions, tips and points, to get me started?

If this is not something we see as it could fit into the current goals of dispatch.vim, that's fine too.

**Comment by tpope** [comment]
There's a lot of ways you could go with this. Do you want it to capture output and show it in a tab or something? My guess that would be convoluted and fiddly and probably something I would avoid merging until I'm sure the kinks are worked out. Running it invisibly, on the other hand, is probably pretty simple and a candidate for a quick merge, though probably a bit less useful.

**Comment by myw** [comment]
From a cursory example, it looks like it would be possible to just add a `dispatch/jobs.vim` file, in which you wrap the existing dispatch commands around the new low-level `:job_` functions/commands in Vim 8. This would be really cool, as it would let existing plugins that depend on `vim-distpatch` transition to using the new built-in job functionality (gaining its perks in speed and reliability) without having to rewrite their own async-handling. Since I haven't actually tried it out, I don't know how many kinks there would be to iron out, but it seems _eminently_ doable, with a large upside. If no one takes this on, I'd look into it over a weekend project.

**Comment by teoljungberg** [comment]
> There's a lot of ways you could go with this. Do you want it to capture output and show it in a tab or something? 

My ideal use case would be to have it work like the other adapters work, to have the errors be read into the quickfix list.

**Comment by tpope** [comment]
Well the other adapters generally have a way to watch the command in progress, in a tmux pane or terminal window or whatever. If that isn't a requirement, it'll probably be pretty simple.

**Comment by tpope** [comment]
Let's centralize discussion in #193.
