### ISSUE TITLE
Is there any means to make colour logs?

### ISSUE THREAD

**Issue by antonstakhouski** [tpope/vim-dispatch#271]
I am running a remote build executing such command
`:execute 'Dispatch ssh username@ip  make  -j4 -C' project_name '2>&1 | ccze -A'`
Durung make execution i see colour logs, but then quickfix window reopens showing error on the first line.
`|| make: Entering directory '/path/to/project/dir'`
All logs are colorless now and are prepended with ||.
Is there are any means to make logs more readable and with proper error parsing?

**Comment by tpope** [comment]
Vim doesn't support ANSI escape sequences in the quickfix list, so colors can't/won't be supported there.

Proper error parsing is based on the executable name. This doesn't play very well with commands like ssh. One thing you can tell it do do is ignore `ssh username@ip` when looking for the executable, so that it sees `make` instead.

```vim
if !exists('g:dispatch_compilers')
  let g:dispatch_compilers = {}
endif
let g:dispatch_compilers['ssh username@ip'] = ''
```

However, I wouldn't expect this to be particularly useful, because the filenames on the remote host aren't going to make sense on the local host.

**Comment by antonstakhouski** [comment]
Thanks, @tpope . Error parsing is now working exactly the same as running buld locally.
I use lsyncd to have a local replica of the project, so editing files and building project is completely transparent now.

**Comment by codeinabox** [comment]
> Vim doesn't support ANSI escape sequences in the quickfix list, so colors can't/won't be supported there.

Would it be possible to have NO_COLORS=1 automatically set where ANSI escape sequences are not supported? The reason I ask is this there is https://github.com/vim-test/vim-test/issues/776, for which I have the fix https://github.com/vim-test/vim-test/pull/777, though I am wondering if this functionality should live in Dispatch? 🤔
