### ISSUE TITLE
Document "Allow embedding default start in 'errorformat'"

### ISSUE THREAD

**Issue by kiryph** [tpope/vim-dispatch#272]
I have noticed the recent commit https://github.com/tpope/vim-dispatch/commit/786feb1f2926f24e4757ffb4d6d104e0a0efcc21 with the commit title and message

> **Allow embedding default start in 'errorformat'**
Being liberal in what I accept because I'm not ready to pick a side in
snake case versus camel case.

I am curious where the `'errorformat'` (`'efm'`) should be defined. In other words I do not get what this commits allows to do.

I also use vim-projectionist and added for my cmake projects the property `compiler` (typically set to `gcc`) which sets `'efm'` 
```viml
let g:projectionist_heuristics = {
      \ "CMakeLists.txt&_builds/debug/Makefile": {
      \   "*": {
      \            "make": "make -C {project}/_builds/debug -j8",
      \            "compiler": "gcc",
     \     }
      \   }
      \ }
```

Since vim-projectionist actually does not have a property`compiler` (e.g. in contrast to [vim-makery](https://github.com/igemnace/vim-makery/blob/master/doc/makery.txt#L44-L57)), I added following autocmd and function

```viml
augroup myprojectionist
    autocmd!
    autocmd User ProjectionistActivate call s:activate()
augroup END

function! s:activate() abort

    for [root, value] in projectionist#query('compiler')
        execute('compiler '.value)
        break
    endfor

endfunction
```

**Comment by tpope** [comment]
In the typical case you would add it to the compiler plugin or the corresponding `after/` file. Something like <https://github.com/tpope/vim-rails/blob/2b33a3df78f337ec44874fa9fb2862ab229614ce/compiler/rails.vim#L55>. I intend to properly document once the interface is finalized.

I originally didn't allow setting the Vim compiler because I wanted to keep it editor agnostic, but it's increasingly apparent to me that's too limiting. One problem with your approach in particular is that you can get weird mixed results if one file sets `compiler` and another sets `make`. This could be fixed with a query API that allows you to ask for multiple keys. Alternatively, I kind of like the idea of putting it all a dictionary:

```json
{
  "*": {
    "make": {
      "program": "bin/rails",
      "vimCompiler": "rails",
      "vimHints": {
        "start": "console"
      }
    }
  }
}
```
