### ISSUE TITLE
makeprg gets overwritten when using cargo

### ISSUE THREAD

**Issue by maujim** [tpope/vim-dispatch#310]
### Expected behaviour
I should be able to run `:Make build` without `makeprg` being modified.

### Issue
The default `makeprg` with cargo is `cargo $*`, obtained by running `set makeprg?`. If I run `:make build`, or `:Make! build`, or `:Dispatch! cargo build`, makeprg stays unchanged.

However, if I run `:Make build` or `:Dispatch cargo build`, `makeprg` get modified to `cargo build`. Thus, running `:Make build` a second time actually runs `cargo build build` and causes `cargo` to throw an error.

The strange thing is that this doesn't happen if there are no compiler warnings/errors. In the code example below, there is a compiler warning for `foo` being unused and this warning gets added to the quickfix list.

Rust allows adding a leading underscore for intentionally unused variables and doing so suppresses the compiler warning so that the quickfix list isn't populated with anything.

In this case, running `:Make build` or `:Dispatch cargo build` does not modify `makeprg`.

#### Minimal example

```rust
// src/main.rs

fn main() {
    let foo = 22;
}
```

### Things I looked into
In `$VIMRUNTIME/compiler/cargo.vim`, there is a variable called `g:cargo_makeprg_params` which is used to pass additional arguments to cargo.
I wonder if this could be related to the issue. However, this variable is never set.

```sh
$ nvim --version
NVIM v0.4.4

Build type: Release

LuaJIT 2.0.5

Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include

Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by tpope** [comment]
`:Dispatch` temporarily sets `'makeprg'` and restores it afterwards. For an asynchronous workflow, this happens once when starting the command and a second time when it finishes. Since `'makeprg'` is buffer local, one thing that can go wrong is if an autocommand changes the current buffer in the interim, causing Dispatch to restore in the wrong buffer. So my first question, is the same buffer in focus at the end as in the beginning? This includes changing to the quickfix window, which Dispatch avoids doing but you might be triggering yourself.

**Comment by maujim** [comment]
Yup that was the issue. I'm using https://github.com/romainl/vim-qf/ which has a feature to automatically open the quickfix list automatically if there are any errors and also jump to it. I have disabled that functionality and no longer get this error.

Thanks for your help!

**Comment by Notgnoshi** [comment]
I apologize for bringing this back up - I'm seeing the same behavior, but with what appears to be a different cause? Or maybe I've horribly misunderstood.

I can reproduce this behavior with the following steps:
1. Open a Rust source file
   1. `:verbose set makeprg?` shows `makeprg=cargo $*` set by `rust.vim/compiler/cargo.vim`
   2. Run `:Make build` and bask in the glorious vim-dispatch awesomesauce
2. My project that I'm procrastinating has a warning, so the quickfix window is opened
   1. While the quickfix list is the active buffer, `:verbose set makeprg?` shows `makeprg=cargo $*` set by `dispatch.vim`
3. Move the cursor from the quickfix window back to the Rust source file
   1. `:verbose set makeprg?` shows `makeprg=cargo build` set by `dispatch.vim`

My original hypothesis was that `$*` was being replaced by its expanded value, but the following test demonstrates that's not true

1. In `after/ftplugin/rust.vim` put `set makeprg=cargo`
2. Open a Rust source file
   1. Sanity check with `:verbose set makeprg?`
   2. Run `:Make build`
3. In the quickfix window, run `:verbose set makeprg?`, which shows `makeprg=cargo` set by `dispatch.vim`
4. Move the cursor back to the Rust source file
   1. `:verbose set makeprg?` shows `makeprg=cargo build` set by `dispatch.vim`

So now my new hypothesis is that `dispatch.vim` is restoring `makeprg` to the expanded command that was run, instead of the previous value of `makeprg`? (maybe here: https://github.com/tpope/vim-dispatch/blob/6cc2691576f97d43f8751664d1a1a908b99927e5/autoload/dispatch.vim#L1328 ?) 

Unfortunately I'm not enough of a vimscriptist to follow `dispatch.vim` well enough to tell for sure - I'm confident there's subtlety that I'm not picking up on.

---

Anyways, I'm able to work around this by adding
```vim
augroup RestoreRustMakeprg
    autocmd!
    autocmd BufEnter * execute 'set makeprg=cargo'
augroup END
```
in `after/ftplugin/rust.vim`

**Comment by tpope** [comment]
> So now my new hypothesis is that `dispatch.vim` is restoring `makeprg` to the expanded command that was run, instead of the previous value of `makeprg`? (maybe here:
> 
> https://github.com/tpope/vim-dispatch/blob/6cc2691576f97d43f8751664d1a1a908b99927e5/autoload/dispatch.vim#L1328

This makes sense as the line that setting it. But it's supposed to be temporary. A few lines later it's restored in a `finally` clause:

https://github.com/tpope/vim-dispatch/blob/6cc2691576f97d43f8751664d1a1a908b99927e5/autoload/dispatch.vim#L1348

The problem is that while it's temporarily set, `QuickFixCmdPost` is run, and you have an autocommand that opens and focuses another window: 

https://github.com/Notgnoshi/dotfiles/blob/67eb12f8b57769c3754f720979c98e495b6dd068/stowdir/.vim/vimrc#L343

So the restore is happening in the wrong window.

I suspect you're the first to run into this because most people with an autocommand like that restore the focus to the original window.

**Comment by Notgnoshi** [comment]
You're 100% right.

I apologize for making you dig through my vimrc - after removing the offending autocommand things work exactly as I expect. This was an entirely self-made problem, and I didn't do the due diligence of verifying I _wasn't_ opening the quickfix window.

I should go through my vimrc and remove the cruft that I no longer remember :sweat_smile:
