### ISSUE TITLE
Crazy characters from dotnet run inside tmux only

### ISSUE THREAD

**Issue by erietz** [tpope/vim-dispatch#322]
Hi tpope. Weird characters are being printed in my C# project when running dispatch with `dotnet run`. This occurs in vim and neovim but only when in tmux. I am on Linux btw. Please see the screenshot below. If this issue is ridiculous please feel free to delete. Thanks tpope.

![2021-12-02-131846_1904x1247_scrot](https://user-images.githubusercontent.com/11425271/144490131-5ab60a42-4d52-4069-aa2b-80022bd73214.png)

**Comment by tpope** [comment]
The tmux adapter uses `tmux pipe-pane` to capture output, rather than redirecting stdout/stderr. The advantage of this approach is you get terminal colors in the tmux split. The disadvantage is that some commands spew a bunch of redundant garbage to the terminal, and filtering it out is a game of whack-a-mole.

This has come up in several issues, so I'm changing the default.
