### ISSUE TITLE
Have an option to use an interactive shell on :Dispatch

### ISSUE THREAD

**Issue by rr-tomas-henriquez** [tpope/vim-dispatch#338]
I love the way :Dispatch works with tmux by opening a tmux pane below as it would on the quickfix. My main problem is when I enter into any situation where I need to interact with code, usually when debugging with python ipdb, it loses all colors, autocomplete, etc.

This doesn't happen when using :Start. It's there a way to make this same "quickfix like" window interactive as in Start?

**Comment by tpope** [comment]
If you're using the tmux adapter you can `let g:dispatch_tmux_pipe_pane = 1`, but note that this may alter what gets captured in undesirable ways. #322 

The official solution to this is use `:0Spawn` or `:.Spawn` instead of `:Dispatch` when you want a terminal. The line number argument tells it to use the same default command as `:Dispatch`. https://github.com/tpope/vim-dispatch/blob/6cc2691576f97d43f8751664d1a1a908b99927e5/doc/dispatch.txt#L131-L133

**Comment by rr-tomas-henriquez** [comment]
Thank you mate! testing it now

**Comment by rr-tomas-henriquez** [comment]
working now, thank you very much sir 💪🏿
