### ISSUE TITLE
Default flags for a command

### ISSUE THREAD

**Issue by saccarosium** [tpope/vim-dispatch#344]
Hi,
Since I use Start to run my programs and see the output. Most of the time, if not always, wants the flag `-wait=always` to actually see the stdout.

I've tried to remap the keybindings, but I have to remember to put the flag always and becomes annoying after a wile.

My propose implementation would be something like:

```vim
let g:dispatch_start_flags = {}
" or
" Let the user disable automatic close
let g:dispatch_wait = "never" | "error" | "always"
```

**Comment by tpope** [comment]
`:Start` is designed for long-running processes, especially interactive processes like REPLs. It's not just a user facing interface, but also an API that other plugins ([example](https://github.com/tpope/vim-dadbod/blob/7888cb7164d69783d3dce4e0283decd26b82538b/autoload/db.vim#L470-L475)) can use for the same purpose. Making `-wait` configurable is not on the table.

Dispatch does provide a feature for seeing the output of a command: `:Dispatch`. If you'd rather not use the quickfix list, your best option is to create a new command with your preferred behavior:

```vim
command! -bang -nargs=* RunWait Spawn -wait=always <args>
```

I'm using `:Spawn` here rather than `:Start` because it disables the "refocus an existing window" behavior you probably don't want/need.
