### ISSUE TITLE
qflist should get populated after command exits and not upon executing `:Copen`

### ISSUE THREAD

**Issue by xz47sv** [tpope/vim-dispatch#349]
The qflist doesn't get updated until the quickfix window is opened (immediately for `:Make`, after `:Copen` for `:Make!`).

I think `dispatch#complete` should populate it regardless if window is about to open, because users might want to interact with the quickfix list without opening the window. Plus `:h QuickFixCmdPost` specifies that it should run after a command is done executing which is not the case for `Make!`.

Simplest fix would be to move `s:cgetfile` call from `s:cwindow` into `dispatch#complete` and call it unconditionally.

**Comment by tpope** [comment]
That's already how it works. If you `:Dispatch true`, the window won't open, but the quickfix list is still populated.

Passing a bang (`:Dispatch!`, `:Make!`) does prevent opening the window _and_ populating the list until you call `:Copen`. This is by design. It dates back to the days when Vim lacked proper async support. These days, it's a very niche feature. It can be used to kick off a very long running task, like a full test suite, and not have to deal with it until you're ready.

> users might want to interact with the quickfix list without opening the window

In practice, trying interact with the Dispatch quickfix list without seeing it is awkward, because jumping to the first error might need a `:cc` (if the first line has a filename) or might need a `:cnext` (if the first line is informative output without a filename). For this reason, Dispatch doesn't provide a way to populate the quickfix list without also revealing it.
