### ISSUE TITLE
Open up a vertical split in tmux

### ISSUE THREAD

**Issue by teoljungberg** [tpope/vim-dispatch#65]
I would love to be able to open up `autotest` as a vertical split in tmux from `dispatch.vim`, could you give some guidance?

**Comment by Zyst** [comment]
Okay so for anyone else finding this from Google, here's how I essentially cheesed a solution to open a 50% vertical split only editing variables.

Add `let g:dispatch_tmux_height = '50% -h'` to your `.vimrc`. Of course you can use whatever you want instead of "50%".

This works because in [this line](https://github.com/tpope/vim-dispatch/blob/250ea269e206445d10700b299afd3eb993e939ad/autoload/dispatch/tmux.vim#L57) we can use `dispatch_tmux_height` to inject a height, so I added the 50% I wanted, and then we add a space ourselves, and pass in `-h` to indicate to Tmux that the split should be horizontal.

The result looks like this using `:Dispatch yarn test %`:

![image](https://user-images.githubusercontent.com/3832380/120055064-5e03c780-bff9-11eb-946a-9d668ec47ec3.png)

Good luck!
