### ISSUE TITLE
Syntax highlighting disabled in working buffer when using vim-dispatch to run python code

### ISSUE THREAD

**Issue by saevarb** [tpope/vim-dispatch#93]
I am currently using vim-dispatch only for running Python code. It's working pretty well, but for some reason, it turns syntax highlighting off, which I can fix by either setting the filetype to python again, or by using `:syntax on`.

This is what the relevant section looks like in my .vimrc.

```
" --------------------------------------------------------------------------
" Python stuff
" --------------------------------------------------------------------------

au! FileType python setl nosmartindent
au FileType python nmap <Leader>r :Dispatch ipython %<CR>
au FileTYpe python nmap <Leader>ar :Dispatch ipython %<Space>
```

The latter keybinding is for being able to pass arguments when needed. Here's the whole .vimrc https://gist.github.com/saevarb/18d0111acd7309ed5dfd#file-vimrc-L121

**Comment by tpope** [comment]
I can't really help with debugging individual configs, but I've seen the "syntax highlighting disabled" issue in other contexts, and usually the culprit is some sort of clever buffer autocommands, typically found in a plugin that does buffer management or something similar. So I recommend disabling other plugins and parts of your vimrc to see if you can get the issue to go away.
